---

- set_fact:
    security_groups:
      # Dependency on the server.
      - name: "sg-role-node_exporter"
        rules: []

      - name: "sg-role-prometheus"
        description: 
        rules:
          - { direction: "egress", protocol: tcp, port: "9100", remote_group: "sg-role-node_exporter", description: "Allow scraping node-expoter" }

- openstack.cloud.security_group:
    state: present
    name: "{{item.name}}"
    description: "{{item.description | default(omit)}}"
  with_items: "{{security_groups}}"

# Delete defualt rules
- include_tasks: "common/delete_default_rules.yaml"

- openstack.cloud.security_group_rule:
    security_group: "{{item.0.name}}" 
    direction: "{{item.1.direction}}" 
    protocol: "{{ item.1.protocol | default(tcp) }}"
    port_range_min: "{{ item.1.port | default(omit)}}"
    port_range_max: "{{ item.1.port | default (omit) }}"
    remote_ip_prefix: "{{item.1.remote_ip_prefix | default(omit)}}"
    remote_group: "{{item.1.remote_group | default(omit)}}"
  loop: "{{ security_groups | subelements('rules') }}"
