---
- hosts: localhost
  tasks:

    - include_vars: "config/defaults.yaml"

    ##
    # == Create security groups routers and networks.
    #

    - block:
        - include_tasks: "networks/net-hahl.yaml"
      tags:
        - "networks"

    - block:
        - include_tasks: "routers/rou-hahl-ext.yaml"
      tags:
        - "routers"

    ## 
    # == Create resources for Applications
    #
    - block:
        # Default internet access
        - include_tasks: "security_groups/sg-allow_internet.yaml"
        - include_tasks: "security_groups/sg-allow_all.yaml"
        - include_tasks: "security_groups/sg-role-egress_email.yaml"

        # SSH Access
        - include_tasks: "security_groups/sg-role-ssh_client.yaml"
        - include_tasks: "security_groups/sg-role-ssh_server.yaml"

        # IdM Client and server
        - include_tasks: "security_groups/sg-role-idm_client.yaml"
        - include_tasks: "security_groups/sg-role-idm_server.yaml"

        # Load Balancer Security Groups
        - include_tasks: "security_groups/sg-role-apps_lb.yaml"
        - include_tasks: "security_groups/sg-role-apps_lb_backend_https.yaml"
        - include_tasks: "security_groups/sg-role-apps_lb_backend_mc.yaml"

        # Kubernetes
        - include_tasks: "security_groups/sg-role-k8s_client.yaml"
        - include_tasks: "security_groups/sg-role-k8s_worker.yaml"
        - include_tasks: "security_groups/sg-role-k8s_master.yaml"
        
        # Prometheus
        - include_tasks: "security_groups/sg-role-prometheus.yaml"
        - include_tasks: "security_groups/sg-role-node_exporter.yaml"
      tags:
        - "security_groups"

    # Ports
    - block:
        - include_tasks: "ports/net-hahl-k8s/grp-infra-k8s.yaml"
        - include_tasks: "ports/net-hahl-apps/grp-apps-lb.yaml"
        - include_tasks: "ports/net-hahl-apps/syd-mc-01.apps.hahl.id.au_Port-1.yaml"
        - include_tasks: "ports/net-hahl-apps/syd-matrix-01.apps.hahl.id.au_Port-1.yaml"
      tags:
        - "ports"

    # Volumes
    - block:
        - include_tasks: "volumes/grp-infra-k8s.yaml"
      tags:
        - "volumes"

    # Instances
    - block:
        - include_tasks: "instances/grp-infra-k8s.yaml"
        - include_tasks: "instances/grp-apps-lb.yaml"
        - include_tasks: "instances/syd-mc-01.apps.hahl.id.au.yaml"
        - include_tasks: "instances/syd-matrix-01.apps.hahl.id.au.yaml"
      tags:
        - "instances"
