---
- hosts: localhost
  tasks:
    ##
    # == Create security groups routers and networks.
    #
    - include_tasks: "security_groups/sg-allow_internet.yaml"
    - include_tasks: "security_groups/sg-allow_all.yaml"
    - include_tasks: "networks/net-hahl.yaml"
    - include_tasks: "routers/rou-hahl-ext.yaml"

    ## 
    # == Create resources for Applications
    #
    - include_tasks: "security_groups/sg-role-apps_lb.yaml"
    - include_tasks: "ports/net-hahl-apps/syd-lb-01.apps.hahl.id.au_Port-1.yaml"
    - include_tasks: "ports/net-hahl-apps/syd-lb-02.apps.hahl.id.au_Port-1.yaml"
    - include_tasks: "ports/net-hahl-apps/syd-lb-vip.apps.hahl.id.au_Port-1.yaml"
